In [1]:
import numpy as np

In [2]:
val1 = np.array([[1,2,3,4],[5,6,7,8]])
val1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
val2 = np.zeros((8,5) , dtype=int)   
val2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [4]:
val3 = np.ones((2,5) , dtype=int)
val3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
val4 = np.arange(6,40,2)
val4

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [6]:
val5 = np.linspace(10,30,5)
val5

array([10., 15., 20., 25., 30.])

In [7]:
val6 = np.random.randint(0,35,size=(4,6))
print(val6)

[[16 28 34 20 17 22]
 [32 30 13 19 34 32]
 [26  7 29 32 30  2]
 [18 28 19  9 33  4]]


In [8]:
val7 = np.full((3,4,3),6)
print(val7)

[[[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]]


In [9]:
val8 = np.identity(5)
print(val8)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
list_ = [1,2,3]
val9 = np.asarray(list_)
val9

array([1, 2, 3])

In [11]:
a = np.random.randint(1,5,(2,4))
a

array([[4, 2, 3, 4],
       [3, 3, 4, 2]])

In [12]:
b = np.random.randint(5,10,(2,4))
b

array([[7, 9, 6, 7],
       [5, 9, 9, 6]])

In [14]:
np.multiply(a,b)

array([[28, 18, 18, 28],
       [15, 27, 36, 12]])

In [15]:
np.divide(a,b)

array([[0.57142857, 0.22222222, 0.5       , 0.57142857],
       [0.6       , 0.33333333, 0.44444444, 0.33333333]])

In [16]:
multiply = np.multiply(186, 300)
multiply

55800

In [17]:
val1 = np.random.randint(1,40,(3,5))
val1

array([[26, 16, 11, 31, 13],
       [36, 34,  2, 38, 28],
       [34, 24, 26, 16, 17]])

In [18]:
val2.max()

0

In [19]:
val3.min()

1

In [20]:
val4 = np.array([[1,2,3],[5,8,4]])
np.median(val4)

3.5

In [21]:
val1 = np.array(np.random.randint(1,5,(4,6)))
val1

array([[4, 4, 3, 2, 1, 4],
       [3, 4, 2, 1, 4, 2],
       [3, 2, 2, 3, 1, 1],
       [2, 3, 1, 4, 3, 3]])

In [22]:
transpose_array = np.transpose(val1)
transpose_array

array([[4, 3, 3, 2],
       [4, 4, 2, 3],
       [3, 2, 2, 1],
       [2, 1, 3, 4],
       [1, 4, 1, 3],
       [4, 2, 1, 3]])

In [23]:
val3.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
val1 = np.array([[1,2,3],[3,4,9]])
print(val1.shape)

(2, 3)
